# Generated by Django 3.2.4 on 2021-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='still_active',
            field=models.BooleanField(default=True),
        ),
    ]
